name: lucid_dreams_aaa
description: AAA Lucid Dreaming App – Knowledge, Research, Studies Feed, Reading List (on-device), Apple-style UI.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.6.18
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.3
  shared_preferences: ^2.5.3
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.39
  workmanager: ^0.5.2
  background_fetch: ^1.2.1
  share_plus: ^10.0.0
  google_fonts: ^6.3.0
  # Neu: MP4-Loops im Header-Slider
  video_player: ^2.9.1
  http: ^1.2.1
  dart_rss: ^3.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: false

  assets:
    - assets/icons/              # Bottom-Nav SVGs
    - assets/slider/             # Header-Slider-Bilder + manifest.json
    - assets/slider/loops/       # MP4-Video-Loops (autoplay, muted)
    - assets/audio/affirmations/
    - assets/audio/
    - assets/logo/logo-signet.svg
    - assets/logo/
    - assets/brand/hero_bg.webp
    - assets/wissen/grundlagen_de.md
    - assets/wissen/klartraum_grundlagen_de.md
    - assets/wissen/techniken_de.md
    - assets/wissen/neuro_sleep_de.md
    - assets/wissen/journal_guide_de.md
    - assets/wissen/albtraeume_irt_de.md
    - assets/wissen/wearables_erkennung_de.md
    - assets/wissen/ethik_risiken_de.md
    - assets/wissen/troubleshooting_de.md
    - assets/wissen/faq_de.md
    - assets/wissen/glossar_de.md
    - assets/wissen/quellen_zitate_de.md
    - assets/wissen/citations_de.md
    - assets/wissen_en/basics_en.md
    - assets/wissen_en/techniques_en.md
    - assets/wissen_en/neuro_sleep_en.md
    - assets/wissen_en/journal_guide_en.md
    - assets/wissen_en/nightmare_irt_en.md
    - assets/wissen_en/wearables_detection_en.md
    - assets/wissen_en/ethics_risks_en.md
    - assets/wissen_en/troubleshooting_en.md
    - assets/wissen_en/faq_en.md
    - assets/wissen_en/glossary_en.md
    - assets/wissen_en/citations_en.md
    - assets/quizzes/techniken_de.json
    - assets/checklists/pre_night_de.json
    - assets/traumreisen/
    - assets/traumreisen/images/
    - assets/traumreisen/audio/
    - assets/logo/logo-text.svg
    - assets/audio/cues/
    - assets/images/cue_categories/
    - assets/fonts/DMSans-Light.ttf
    - assets/meditations/manifest.json
    - assets/meditations/
    - assets/meditations/tracks/
    - assets/meditations/covers/
    - assets/feed/sources.json
    - assets/feed/curated.json
    - assets/wissen/
    - assets/audio/affirmations/


  # Optional, aber empfohlen: DM Sans lokal einbetten (passt zu allowRuntimeFetching=false)
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
