name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]   # passe an, falls dein Default-Branch anders heißt
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (inkl. LFS für Audio)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      # WICHTIG: Bei Projekt-Page base-href = /lucid/
      - name: Build Flutter Web (Projekt-Page)
        run: |
          flutter build web --release --base-href "/lucid/" --pwa-strategy=none
          cp build/web/index.html build/web/404.html
          touch build/web/.nojekyll
          # Optional: Custom Domain via Secret CUSTOM_DOMAIN
          if [ -n "${{ secrets.CUSTOM_DOMAIN }}" ]; then
            echo "${{ secrets.CUSTOM_DOMAIN }}" > build/web/CNAME
          fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
